language: node_js

node_js:
 - "0.10"

before_install:
  - sudo pip install codecov

install:
 - npm install

services:
 - mongodb

addons:
 postgresql: "9.2"


before_script:
  - echo 'sleep 15 and create db user'
  - sleep 15
  - mongo test --eval 'db.addUser("test", "test");'
  - psql -c 'create database testdb;' -U postgres
  - psql -c "CREATE USER test WITH UNENCRYPTED PASSWORD 'test' " -U postgres
  - psql testdb -c "CREATE EXTENSION hstore SCHEMA public;" -U postgres


after_success:
  - codecov

script:
  - npm test

