language: node_js
 
node_js:
 - "0.10"

install:
 - npm install

services:
 - mongodb

before_script:
  - echo 'sleep 15 and create db user'
  - sleep 15
  - mongo test --eval 'db.addUser("test", "test");'

script:
  - npm test
