language: node_js

node_js:
 - "0.10"



install:
 - npm install

services:
 - mongodb

addons:
 postgresql: "9.3"


before_script:
  - echo 'sleep 15 and create db user'
  - sleep 15
  - mongo test --eval 'db.addUser("test", "test");'
  - psql -c 'create database testdb;' -U postgres
  - psql -c "CREATE USER test WITH UNENCRYPTED PASSWORD 'test' " -U postgres
  - psql testdb -c "CREATE EXTENSION hstore SCHEMA public;" -U postgres




script:
  - export CODECOV_TOKEN="da541dee-74f2-45e3-9d3f-4962fa9e15d0"
  - npm test

