 language: node_js
 
 node_js:
   - "0.10"

install:
  - echo 'hello World'

services:
  - mongodb

before_script:
  - "sleep 15"
  - "mongo test --eval 'db.addUser("test", "test");'"

script:
  - "npm test"
