exports.dachKeyList = {"DE":{name:"Deutschland"},'DE01003':{name:'Lübeck',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'01003'},
'DE01004':{name:'Neumünster',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'01004'},
'DE01051':{name:'Kreis Dithmarschen',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'01051'},
'DE01053':{name:'Kreis Herzogtum Lauenburg',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'01053'},
'DE01054':{name:'Kreis Nordfriesland',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'01054'},
'DE01055':{name:'Kreis Ostholstein',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'01055'},
'DE01056':{name:'Kreis Pinneberg',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'01056'},
'DE01057':{name:'Kreis Plön',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'01057'},
'DE01058':{name:'Kreis Rendsburg-Eckernförde',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'01058'},
'DE01059':{name:'Kreis Schleswig-Flensburg',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'01059'},
'DE01060':{name:'Kreis Segeberg',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'01060'},
'DE01061':{name:'Kreis Steinburg',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'01061'},
'DE01062':{name:'Kreis Stormarn',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'01062'},
'DE02000':{name:'Hamburg',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'02000'},
'DE03101':{name:'Braunschweig',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'03101'},
'DE03102':{name:'Salzgitter',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'03102'},
'DE03103':{name:'Wolfsburg',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'03103'},
'DE03151':{name:'Landkreis Gifhorn',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'03151'},
'DE03152':{name:'Landkreis Göttingen',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'03152'},
'DE03153':{name:'Landkreis Goslar',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'03153'},
'DE03154':{name:'Landkreis Helmstedt',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'03154'},
'DE03155':{name:'Landkreis Northeim',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'03155'},
'DE03156':{name:'Landkreis Osterode am Harz',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'03156'},
'DE03157':{name:'Landkreis Peine',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'03157'},
'DE03158':{name:'Landkreis Wolfenbüttel',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'03158'},
'DE03241':{name:'Region Hannover',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'03241'},
'DE03251':{name:'Landkreis Diepholz',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'03251'},
'DE03252':{name:'Landkreis Hameln-Pyrmont',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'03252'},
'DE03254':{name:'Landkreis Hildesheim',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'03254'},
'DE03255':{name:'Landkreis Holzminden',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'03255'},
'DE03256':{name:'Landkreis Nienburg/Weser',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'03256'},
'DE03257':{name:'Landkreis Schaumburg',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'03257'},
'DE03351':{name:'Landkreis Celle',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'03351'},
'DE03352':{name:'Landkreis Cuxhaven',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'03352'},
'DE03353':{name:'Landkreis Harburg',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'03353'},
'DE03354':{name:'Landkreis Lüchow-Dannenberg',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'03354'},
'DE03355':{name:'Landkreis Lüneburg',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'03355'},
'DE03356':{name:'Landkreis Osterholz',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'03356'},
'DE03357':{name:'Landkreis Rotenburg (Wümme)',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'03357'},
'DE03358':{name:'Landkreis Heidekreis',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'03358'},
'DE03359':{name:'Landkreis Stade',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'03359'},
'DE03360':{name:'Landkreis Uelzen',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'03360'},
'DE03361':{name:'Landkreis Verden',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'03361'},
'DE03401':{name:'Delmenhorst',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'03401'},
'DE03402':{name:'Emden',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'03402'},
'DE03403':{name:'Oldenburg',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'03403'},
'DE03404':{name:'Osnabrück',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'03404'},
'DE03405':{name:'Wilhelmshaven',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'03405'},
'DE03451':{name:'Landkreis Ammerland',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'03451'},
'DE03452':{name:'Landkreis Aurich',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'03452'},
'DE03453':{name:'Landkreis Cloppenburg',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'03453'},
'DE03454':{name:'Landkreis Emsland',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'03454'},
'DE03455':{name:'Landkreis Friesland',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'03455'},
'DE03456':{name:'Landkreis Grafschaft Bentheim',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'03456'},
'DE03457':{name:'Landkreis Leer',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'03457'},
'DE03458':{name:'Landkreis Oldenburg',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'03458'},
'DE03459':{name:'Landkreis Osnabrück',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'03459'},
'DE03460':{name:'Landkreis Vechta',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'03460'},
'DE03461':{name:'Landkreis Wesermarsch',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'03461'},
'DE03462':{name:'Landkreis Wittmund',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'03462'},
'DE04011':{name:'Bremen',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'04011'},
'DE04012':{name:'Bremerhaven',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'04012'},
'DE05111':{name:'Düsseldorf',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'05111'},
'DE05112':{name:'Duisburg',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'05112'},
'DE05113':{name:'Essen',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'05113'},
'DE05114':{name:'Krefeld',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'05114'},
'DE05116':{name:'Mönchengladbach',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'05116'},
'DE05117':{name:'Mülheim an der Ruhr',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'05117'},
'DE05119':{name:'Oberhausen',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'05119'},
'DE05120':{name:'Remscheid',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'05120'},
'DE05122':{name:'Solingen',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'05122'},
'DE05124':{name:'Wuppertal',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'05124'},
'DE05154':{name:'Kreis Kleve',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'05154'},
'DE05158':{name:'Kreis Mettmann',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'05158'},
'DE05162':{name:'Rhein-Kreis Neuss',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'05162'},
'DE05166':{name:'Kreis Viersen',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'05166'},
'DE05170':{name:'Kreis Wesel',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'05170'},
'DE05314':{name:'Bonn',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'05314'},
'DE05315':{name:'Köln',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'05315'},
'DE05316':{name:'Leverkusen',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'05316'},
'DE05334':{name:'Städteregion Aachen',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'05334'},
'DE05358':{name:'Kreis Düren',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'05358'},
'DE05362':{name:'Rhein-Erft-Kreis',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'05362'},
'DE05366':{name:'Kreis Euskirchen',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'05366'},
'DE05370':{name:'Kreis Heinsberg',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'05370'},
'DE05374':{name:'Oberbergischer Kreis',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'05374'},
'DE05378':{name:'Rheinisch-Bergischer Kreis',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'05378'},
'DE05382':{name:'Rhein-Sieg-Kreis',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'05382'},
'DE05512':{name:'Bottrop',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'05512'},
'DE05513':{name:'Gelsenkirchen',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'05513'},
'DE05515':{name:'Münster',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'05515'},
'DE05554':{name:'Kreis Borken',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'05554'},
'DE05558':{name:'Kreis Coesfeld',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'05558'},
'DE05562':{name:'Kreis Recklinghausen',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'05562'},
'DE05566':{name:'Kreis Steinfurt',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'05566'},
'DE05570':{name:'Kreis Warendorf',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'05570'},
'DE05711':{name:'Bielefeld',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'05711'},
'DE05754':{name:'Kreis Gütersloh',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'05754'},
'DE05758':{name:'Kreis Herford',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'05758'},
'DE05762':{name:'Kreis Höxter',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'05762'},
'DE05766':{name:'Kreis Lippe',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'05766'},
'DE05770':{name:'Kreis Minden-Lübbecke',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'05770'},
'DE05774':{name:'Kreis Paderborn',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'05774'},
'DE05911':{name:'Bochum',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'05911'},
'DE05913':{name:'Dortmund',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'05913'},
'DE05914':{name:'Hagen',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'05914'},
'DE05915':{name:'Hamm',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'05915'},
'DE05916':{name:'Herne',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'05916'},
'DE05954':{name:'Ennepe-Ruhr-Kreis',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'05954'},
'DE05958':{name:'Hochsauerlandkreis',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'05958'},
'DE05962':{name:'Märkischer Kreis',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'05962'},
'DE05966':{name:'Kreis Olpe',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'05966'},
'DE05970':{name:'Kreis Siegen-Wittgenstein',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'05970'},
'DE05974':{name:'Kreis Soest',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'05974'},
'DE05978':{name:'Kreis Unna',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'05978'},
'DE06411':{name:'Darmstadt',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'06411'},
'DE06412':{name:'Frankfurt am Main',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'06412'},
'DE06413':{name:'Offenbach am Main',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'06413'},
'DE06414':{name:'Wiesbaden',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'06414'},
'DE06431':{name:'Kreis Bergstraße',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'06431'},
'DE06432':{name:'Landkreis Darmstadt-Dieburg',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'06432'},
'DE06433':{name:'Kreis Groß-Gerau',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'06433'},
'DE06434':{name:'Hochtaunuskreis',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'06434'},
'DE06435':{name:'Main-Kinzig-Kreis',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'06435'},
'DE06436':{name:'Main-Taunus-Kreis',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'06436'},
'DE06437':{name:'Odenwaldkreis',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'06437'},
'DE06438':{name:'Landkreis Offenbach',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'06438'},
'DE06439':{name:'Rheingau-Taunus-Kreis',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'06439'},
'DE06440':{name:'Wetteraukreis',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'06440'},
'DE06531':{name:'Landkreis Gießen',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'06531'},
'DE06532':{name:'Lahn-Dill-Kreis',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'06532'},
'DE06533':{name:'Landkreis Limburg-Weilburg',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'06533'},
'DE06534':{name:'Landkreis Marburg-Biedenkopf',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'06534'},
'DE06535':{name:'Vogelsbergkreis',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'06535'},
'DE06611':{name:'Kassel',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'06611'},
'DE06631':{name:'Landkreis Fulda',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'06631'},
'DE06632':{name:'Landkreis Hersfeld-Rotenburg',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'06632'},
'DE06633':{name:'Landkreis Kassel',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'06633'},
'DE06634':{name:'Schwalm-Eder-Kreis',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'06634'},
'DE06635':{name:'Landkreis Waldeck-Frankenberg',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'06635'},
'DE06636':{name:'Werra-Meißner-Kreis',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'06636'},
'DE7000999':{name:'Gemeinsames deutsch-luxemburgisches Hoheitsgebiet',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'7000999'},
'DE07111':{name:'Koblenz',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'07111'},
'DE07131':{name:'Landkreis Ahrweiler',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'07131'},
'DE07132':{name:'Landkreis Altenkirchen',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'07132'},
'DE07133':{name:'Landkreis Bad Kreuznach',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'07133'},
'DE07134':{name:'Landkreis Birkenfeld',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'07134'},
'DE07135':{name:'Landkreis Cochem-Zell',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'07135'},
'DE07137':{name:'Landkreis Mayen-Koblenz',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'07137'},
'DE07138':{name:'Landkreis Neuwied',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'07138'},
'DE07140':{name:'Rhein-Hunsrück-Kreis',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'07140'},
'DE07141':{name:'Rhein-Lahn-Kreis',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'07141'},
'DE07143':{name:'Westerwaldkreis',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'07143'},
'DE07211':{name:'Trier',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'07211'},
'DE07231':{name:'Landkreis Bernkastel-Wittlich',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'07231'},
'DE07232':{name:'Eifelkreis Bitburg-Prüm',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'07232'},
'DE07233':{name:'Landkreis Vulkaneifel',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'07233'},
'DE07235':{name:'Landkreis Trier-Saarburg',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'07235'},
'DE07311':{name:'Frankenthal (Pfalz)',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'07311'},
'DE07312':{name:'Kaiserslautern',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'07312'},
'DE07313':{name:'Landau in der Pfalz',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'07313'},
'DE07314':{name:'Ludwigshafen am Rhein',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'07314'},
'DE07315':{name:'Mainz',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'07315'},
'DE07316':{name:'Neustadt an der Weinstraße',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'07316'},
'DE07317':{name:'Pirmasens',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'07317'},
'DE07318':{name:'Speyer',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'07318'},
'DE07319':{name:'Worms',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'07319'},
'DE07320':{name:'Zweibrücken',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'07320'},
'DE07331':{name:'Landkreis Alzey-Worms',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'07331'},
'DE07332':{name:'Landkreis Bad Dürkheim',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'07332'},
'DE07333':{name:'Donnersbergkreis',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'07333'},
'DE07334':{name:'Landkreis Germersheim',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'07334'},
'DE07335':{name:'Landkreis Kaiserslautern',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'07335'},
'DE07336':{name:'Landkreis Kusel',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'07336'},
'DE07337':{name:'Landkreis Südliche Weinstraße',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'07337'},
'DE07338':{name:'Rhein-Pfalz-Kreis',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'07338'},
'DE07339':{name:'Landkreis Mainz-Bingen',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'07339'},
'DE07340':{name:'Landkreis Südwestpfalz',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'07340'},
'DE08111':{name:'Stuttgart',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'08111'},
'DE08115':{name:'Landkreis Böblingen',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'08115'},
'DE08116':{name:'Landkreis Esslingen',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'08116'},
'DE08117':{name:'Landkreis Göppingen',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'08117'},
'DE08118':{name:'Landkreis Ludwigsburg',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'08118'},
'DE08119':{name:'Rems-Murr-Kreis',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'08119'},
'DE08121':{name:'Heilbronn',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'08121'},
'DE08125':{name:'Landkreis Heilbronn',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'08125'},
'DE08126':{name:'Hohenlohekreis',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'08126'},
'DE08127':{name:'Landkreis Schwäbisch Hall',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'08127'},
'DE08128':{name:'Main-Tauber-Kreis',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'08128'},
'DE08135':{name:'Landkreis Heidenheim',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'08135'},
'DE08136':{name:'Ostalbkreis',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'08136'},
'DE08211':{name:'Baden-Baden',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'08211'},
'DE08212':{name:'Karlsruhe',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'08212'},
'DE08215':{name:'Landkreis Karlsruhe',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'08215'},
'DE08216':{name:'Landkreis Rastatt',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'08216'},
'DE08221':{name:'Heidelberg',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'08221'},
'DE08222':{name:'Mannheim',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'08222'},
'DE08225':{name:'Neckar-Odenwald-Kreis',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'08225'},
'DE08226':{name:'Rhein-Neckar-Kreis',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'08226'},
'DE08231':{name:'Pforzheim',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'08231'},
'DE08235':{name:'Landkreis Calw',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'08235'},
'DE08236':{name:'Enzkreis',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'08236'},
'DE08237':{name:'Landkreis Freudenstadt',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'08237'},
'DE08311':{name:'Freiburg im Breisgau',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'08311'},
'DE08315':{name:'Landkreis Breisgau-Hochschwarzwald',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'08315'},
'DE08316':{name:'Landkreis Emmendingen',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'08316'},
'DE08317':{name:'Ortenaukreis',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'08317'},
'DE08325':{name:'Landkreis Rottweil',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'08325'},
'DE08326':{name:'Schwarzwald-Baar-Kreis',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'08326'},
'DE08327':{name:'Landkreis Tuttlingen',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'08327'},
'DE08335':{name:'Landkreis Konstanz',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'08335'},
'DE08336':{name:'Landkreis Lörrach',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'08336'},
'DE08337':{name:'Landkreis Waldshut',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'08337'},
'DE08415':{name:'Landkreis Reutlingen',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'08415'},
'DE08416':{name:'Landkreis Tübingen',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'08416'},
'DE08417':{name:'Zollernalbkreis',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'08417'},
'DE08421':{name:'Ulm',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'08421'},
'DE08425':{name:'Alb-Donau-Kreis',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'08425'},
'DE08426':{name:'Landkreis Biberach',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'08426'},
'DE08435':{name:'Bodenseekreis',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'08435'},
'DE08436':{name:'Landkreis Ravensburg',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'08436'},
'DE08437':{name:'Landkreis Sigmaringen',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'08437'},
'DE09161':{name:'Ingolstadt',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09161'},
'DE09162':{name:'München',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09162'},
'DE09163':{name:'Rosenheim',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09163'},
'DE09171':{name:'Landkreis Altötting',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09171'},
'DE09172':{name:'Landkreis Berchtesgadener Land',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09172'},
'DE09173':{name:'Landkreis Bad Tölz-Wolfratshausen',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09173'},
'DE09174':{name:'Landkreis Dachau',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09174'},
'DE09175':{name:'Landkreis Ebersberg',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09175'},
'DE09176':{name:'Landkreis Eichstätt',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09176'},
'DE09177':{name:'Landkreis Erding',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09177'},
'DE09178':{name:'Landkreis Freising',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09178'},
'DE09179':{name:'Landkreis Fürstenfeldbruck',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09179'},
'DE09180':{name:'Landkreis Garmisch-Partenkirchen',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09180'},
'DE09181':{name:'Landkreis Landsberg am Lech',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09181'},
'DE09182':{name:'Landkreis Miesbach',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09182'},
'DE09183':{name:'Landkreis Mühldorf am Inn',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09183'},
'DE09184':{name:'Landkreis München',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09184'},
'DE09185':{name:'Landkreis Neuburg-Schrobenhausen',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09185'},
'DE09186':{name:'Landkreis Pfaffenhofen an der Ilm',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09186'},
'DE09187':{name:'Landkreis Rosenheim',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09187'},
'DE09188':{name:'Landkreis Starnberg',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09188'},
'DE09189':{name:'Landkreis Traunstein',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09189'},
'DE09190':{name:'Landkreis Weilheim-Schongau',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09190'},
'DE09261':{name:'Landshut',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09261'},
'DE09262':{name:'Passau',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09262'},
'DE09263':{name:'Straubing',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09263'},
'DE09271':{name:'Landkreis Deggendorf',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09271'},
'DE09272':{name:'Landkreis Freyung-Grafenau',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09272'},
'DE09273':{name:'Landkreis Kelheim',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09273'},
'DE09274':{name:'Landkreis Landshut',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09274'},
'DE09275':{name:'Landkreis Passau',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09275'},
'DE09276':{name:'Landkreis Regen',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09276'},
'DE09277':{name:'Landkreis Rottal-Inn',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09277'},
'DE09278':{name:'Landkreis Straubing-Bogen',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09278'},
'DE09279':{name:'Landkreis Dingolfing-Landau',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09279'},
'DE09361':{name:'Amberg',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09361'},
'DE09362':{name:'Regensburg',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09362'},
'DE09363':{name:'Weiden i.d.OPf',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09363'},
'DE09371':{name:'Landkreis Amberg-Sulzbach',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09371'},
'DE09372':{name:'Landkreis Cham',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09372'},
'DE09373':{name:'Landkreis Neumarkt in der Oberpfalz',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09373'},
'DE09374':{name:'Landkreis Neustadt an der Waldnaab',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09374'},
'DE09375':{name:'Landkreis Regensburg',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09375'},
'DE09376':{name:'Landkreis Schwandorf',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09376'},
'DE09377':{name:'Landkreis Tirschenreuth',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09377'},
'DE09461':{name:'Bamberg',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09461'},
'DE09462':{name:'Bayreuth',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09462'},
'DE09463':{name:'Coburg',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09463'},
'DE09464':{name:'Hof',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09464'},
'DE09471':{name:'Landkreis Bamberg',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09471'},
'DE09472':{name:'Landkreis Bayreuth',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09472'},
'DE09473':{name:'Landkreis Coburg',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09473'},
'DE09474':{name:'Landkreis Forchheim',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09474'},
'DE09475':{name:'Landkreis Hof',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09475'},
'DE09476':{name:'Landkreis Kronach',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09476'},
'DE09477':{name:'Landkreis Kulmbach',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09477'},
'DE09478':{name:'Landkreis Lichtenfels',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09478'},
'DE09479':{name:'Landkreis Wunsiedel im Fichtelgebirge',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09479'},
'DE09561':{name:'Ansbach',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09561'},
'DE09562':{name:'Erlangen',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09562'},
'DE09563':{name:'Fürth',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09563'},
'DE09564':{name:'Nürnberg',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09564'},
'DE09565':{name:'Schwabach',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09565'},
'DE09571':{name:'Landkreis Ansbach',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09571'},
'DE09572':{name:'Landkreis Erlangen-Höchstadt',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09572'},
'DE09573':{name:'Landkreis Fürth',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09573'},
'DE09574':{name:'Landkreis Nürnberger Land',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09574'},
'DE09575':{name:'Landkreis Neustadt an der Aisch-Bad Windsheim',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09575'},
'DE09576':{name:'Landkreis Roth',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09576'},
'DE09577':{name:'Landkreis Weißenburg-Gunzenhausen',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09577'},
'DE09661':{name:'Aschaffenburg',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09661'},
'DE09662':{name:'Schweinfurt',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09662'},
'DE09663':{name:'Würzburg',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09663'},
'DE09671':{name:'Landkreis Aschaffenburg',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09671'},
'DE09672':{name:'Landkreis Bad Kissingen',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09672'},
'DE09673':{name:'Landkreis Rhön-Grabfeld',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09673'},
'DE09674':{name:'Landkreis Haßberge',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09674'},
'DE09675':{name:'Landkreis Kitzingen',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09675'},
'DE09676':{name:'Landkreis Miltenberg',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09676'},
'DE09677':{name:'Landkreis Main-Spessart',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09677'},
'DE09678':{name:'Landkreis Schweinfurt',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09678'},
'DE09679':{name:'Landkreis Würzburg',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09679'},
'DE09761':{name:'Augsburg',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09761'},
'DE09762':{name:'Kaufbeuren',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09762'},
'DE09763':{name:'Kempten (Allgäu)',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09763'},
'DE09764':{name:'Memmingen',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09764'},
'DE09771':{name:'Landkreis Aichach-Friedberg',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09771'},
'DE09772':{name:'Landkreis Augsburg',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09772'},
'DE09773':{name:'Landkreis Dillingen an der Donau',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09773'},
'DE09774':{name:'Landkreis Günzburg',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09774'},
'DE09775':{name:'Landkreis Neu-Ulm',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09775'},
'DE09776':{name:'Landkreis Lindau',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09776'},
'DE09777':{name:'Landkreis Ostallgäu',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09777'},
'DE09778':{name:'Landkreis Unterallgäu',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09778'},
'DE09779':{name:'Landkreis Donau-Ries',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09779'},
'DE09780':{name:'Landkreis Oberallgäu',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09780'},
'DE10041':{name:'Regionalverband Saarbrücken',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'10041'},
'DE10042':{name:'Landkreis Merzig-Wadern',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'10042'},
'DE10043':{name:'Landkreis Neunkirchen',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'10043'},
'DE10044':{name:'Landkreis Saarlouis',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'10044'},
'DE10045':{name:'Saarpfalz-Kreis',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'10045'},
'DE10046':{name:'Landkreis St. Wendel',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'10046'},
'DE11000':{name:'Berlin',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'11000'},
'DE12051':{name:'Brandenburg an der Havel',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'12051'},
'DE12052':{name:'Cottbus',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'12052'},
'DE12053':{name:'Frankfurt (Oder)',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'12053'},
'DE12054':{name:'Potsdam',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'12054'},
'DE12060':{name:'Landkreis Barnim',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'12060'},
'DE12061':{name:'Landkreis Dahme-Spreewald',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'12061'},
'DE12062':{name:'Landkreis Elbe-Elster',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'12062'},
'DE12063':{name:'Landkreis Havelland',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'12063'},
'DE12064':{name:'Landkreis Märkisch-Oderland',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'12064'},
'DE12065':{name:'Landkreis Oberhavel',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'12065'},
'DE12066':{name:'Landkreis Oberspreewald-Lausitz',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'12066'},
'DE12067':{name:'Landkreis Oder-Spree',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'12067'},
'DE12068':{name:'Landkreis Ostprignitz-Ruppin',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'12068'},
'DE12069':{name:'Landkreis Potsdam-Mittelmark',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'12069'},
'DE12070':{name:'Landkreis Prignitz',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'12070'},
'DE12071':{name:'Landkreis Spree-Neiße',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'12071'},
'DE12072':{name:'Landkreis Teltow-Fläming',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'12072'},
'DE12073':{name:'Landkreis Uckermark',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'12073'},
'DE13000':{name:'13000',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'13000'},
'DE13003':{name:'Rostock',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'13003'},
'DE13004':{name:'Schwerin',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'13004'},
'DE13071':{name:'Landkreis Mecklenburgische Seenplatte',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'13071'},
'DE13072':{name:'Landkreis Rostock',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'13072'},
'DE13073':{name:'Landkreis Vorpommern-Rügen',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'13073'},
'DE13074':{name:'Landkreis Nordwestmecklenburg',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'13074'},
'DE13075':{name:'Landkreis Vorpommern-Greifswald',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'13075'},
'DE13076':{name:'Landkreis Ludwigslust-Parchim',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'13076'},
'DE14511':{name:'Chemnitz',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'14511'},
'DE14521':{name:'Erzgebirgskreis',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'14521'},
'DE14522':{name:'Landkreis Mittelsachsen',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'14522'},
'DE14523':{name:'Vogtlandkreis',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'14523'},
'DE14524':{name:'Landkreis Zwickau',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'14524'},
'DE14612':{name:'Dresden',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'14612'},
'DE14625':{name:'Landkreis Bautzen',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'14625'},
'DE14626':{name:'Landkreis Görlitz',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'14626'},
'DE14627':{name:'Landkreis Meißen',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'14627'},
'DE14628':{name:'Landkreis Sächsische Schweiz-Osterzgebirge',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'14628'},
'DE14713':{name:'Leipzig',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'14713'},
'DE14729':{name:'Landkreis Leipzig',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'14729'},
'DE14730':{name:'Landkreis Nordsachsen',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'14730'},
'DE15001':{name:'Dessau-Roßlau',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'15001'},
'DE15002':{name:'Halle (Saale)',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'15002'},
'DE15003':{name:'Magdeburg',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'15003'},
'DE15081':{name:'Altmarkkreis Salzwedel',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'15081'},
'DE15082':{name:'Landkreis Anhalt-Bitterfeld',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'15082'},
'DE15083':{name:'Landkreis Börde',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'15083'},
'DE15084':{name:'Burgenlandkreis',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'15084'},
'DE15085':{name:'Landkreis Harz',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'15085'},
'DE15086':{name:'Landkreis Jerichower Land',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'15086'},
'DE15087':{name:'Landkreis Mansfeld-Südharz',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'15087'},
'DE15088':{name:'Saalekreis',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'15088'},
'DE15089':{name:'Salzlandkreis',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'15089'},
'DE15090':{name:'Landkreis Stendal',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'15090'},
'DE15091':{name:'Landkreis Wittenberg',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'15091'},
'DE16051':{name:'Erfurt',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'16051'},
'DE16052':{name:'Gera',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'16052'},
'DE16053':{name:'Jena',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'16053'},
'DE16054':{name:'Suhl',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'16054'},
'DE16055':{name:'Weimar',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'16055'},
'DE16056':{name:'Eisenach',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'16056'},
'DE16061':{name:'Landkreis Eichsfeld',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'16061'},
'DE16062':{name:'Landkreis Nordhausen',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'16062'},
'DE16063':{name:'Wartburgkreis',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'16063'},
'DE16064':{name:'Unstrut-Hainich-Kreis',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'16064'},
'DE16065':{name:'Kyffhäuserkreis',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'16065'},
'DE16066':{name:'Landkreis Schmalkalden-Meiningen',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'16066'},
'DE16067':{name:'Landkreis Gotha',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'16067'},
'DE16068':{name:'Landkreis Sömmerda',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'16068'},
'DE16069':{name:'Landkreis Hildburghausen',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'16069'},
'DE16070':{name:'Ilm-Kreis',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'16070'},
'DE16071':{name:'Landkreis Weimarer Land',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'16071'},
'DE16072':{name:'Landkreis Sonneberg',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'16072'},
'DE16073':{name:'Landkreis Saalfeld-Rudolstadt',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'16073'},
'DE16074':{name:'Saale-Holzland-Kreis',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'16074'},
'DE16075':{name:'Saale-Orla-Kreis',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'16075'},
'DE16076':{name:'Landkreis Greiz',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'16076'},
'DE16077':{name:'Landkreis Altenburger Land',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'16077'},
'DE0106':{name:'Kreis Segeberg'},
'DE0200':{name:'Hamburg'},
'DE0336':{name:'Landkreis Uelzen'},
'DE0346':{name:'Landkreis Vechta'},
'DE0512':{name:'Remscheid'},
'DE0517':{name:'Kreis Wesel'},
'DE0537':{name:'Kreis Heinsberg'},
'DE0557':{name:'Kreis Warendorf'},
'DE0577':{name:'Kreis Minden-Lübbecke'},
'DE0597':{name:'Kreis Siegen-Wittgenstein'},
'DE0644':{name:'Wetteraukreis'},
'DE0714':{name:'Rhein-Hunsrück-Kreis'},
'DE0732':{name:'Zweibrücken'},
'DE0734':{name:'Landkreis Südwestpfalz'},
'DE0918':{name:'Landkreis Garmisch-Partenkirchen'},
'DE0919':{name:'Landkreis Weilheim-Schongau'},
'DE0978':{name:'Landkreis Oberallgäu'},
'DE1100':{name:'Berlin'},
'DE1206':{name:'Landkreis Barnim'},
'DE1207':{name:'Landkreis Prignitz'},
'DE1473':{name:'Landkreis Nordsachsen'},
'DE1509':{name:'Landkreis Stendal'},
'DE1607':{name:'Ilm-Kreis'},
'DE081':{name:'Regierungsbezirk Stuttgart'},
'DE051':{name:'Regierungsbezirk Düsseldorf'},
'DE053':{name:'Regierungsbezirk Köln'},
'DE055':{name:'Regierungsbezirk Münster'},
'DE057':{name:'Regierungsbezirk Detmold'},
'DE059':{name:'Regierungsbezirk Arnsberg'},
'DE064':{name:'Regierungsbezirk Darmstadt'},
'DE065':{name:'Regierungsbezirk Gießen'},
'DE066':{name:'Regierungsbezirk Kassel'},
'DE020':{name:'Hamburg'},
'DE082':{name:'Regierungsbezirk Karlsruhe'},
'DE083':{name:'Regierungsbezirk Freiburg'},
'DE084':{name:'Regierungsbezirk Tübingen'},
'DE091':{name:'Oberbayern'},
'DE092':{name:'Niederbayern'},
'DE093':{name:'Oberpfalz'},
'DE094':{name:'Oberfranken'},
'DE095':{name:'Mittelfranken'},
'DE096':{name:'Unterfranken'},
'DE097':{name:'Schwaben'},
'DE110':{name:'Berlin'},
'DE09':{name:'Bayern'},
'DE01':{name:'Schleswig-Holstein'},
'DE03':{name:'Niedersachsen'},
'DE04':{name:'Bremen'},
'DE05':{name:'Nordrhein-Westfalen'},
'DE06':{name:'Hessen'},
'DE07':{name:'Rheinland-Pfalz'},
'DE08':{name:'Baden-Württemberg'},
'DE02':{name:'Hamburg'},
'DE10':{name:'Saarland'},
'DE11':{name:'Berlin'},
'DE12':{name:'Brandenburg'},
'DE13':{name:'Mecklenburg-Vorpommern'},
'DE14':{name:'Sachsen'},
'DE15':{name:'Sachsen-Anhalt'},
'DE16':{name:'Thüringen'},
'AT416':{name:'Urfahr-Umgebung',osmkey:'ref:at:gkz',osmvalue:'416'},
'AT101':{name:'Eisenstadt (Stadt)',osmkey:'ref:at:gkz',osmvalue:'101'},
'AT103':{name:'Eisenstadt-Umgebung',osmkey:'ref:at:gkz',osmvalue:'103'},
'AT104':{name:'Güssing',osmkey:'ref:at:gkz',osmvalue:'104'},
'AT105':{name:'Jennersdorf',osmkey:'ref:at:gkz',osmvalue:'105'},
'AT106':{name:'Mattersburg',osmkey:'ref:at:gkz',osmvalue:'106'},
'AT107':{name:'Neusiedl am See',osmkey:'ref:at:gkz',osmvalue:'107'},
'AT108':{name:'Oberpullendorf',osmkey:'ref:at:gkz',osmvalue:'108'},
'AT109':{name:'Oberwart',osmkey:'ref:at:gkz',osmvalue:'109'},
'AT202':{name:'Villach (Stadt)',osmkey:'ref:at:gkz',osmvalue:'202'},
'AT203':{name:'Hermagor',osmkey:'ref:at:gkz',osmvalue:'203'},
'AT204':{name:'Klagenfurt-Land',osmkey:'ref:at:gkz',osmvalue:'204'},
'AT205':{name:'Sankt Veit an der Glan',osmkey:'ref:at:gkz',osmvalue:'205'},
'AT206':{name:'Spittal an der Drau',osmkey:'ref:at:gkz',osmvalue:'206'},
'AT207':{name:'Villach-Land',osmkey:'ref:at:gkz',osmvalue:'207'},
'AT208':{name:'Völkermarkt',osmkey:'ref:at:gkz',osmvalue:'208'},
'AT209':{name:'Wolfsberg',osmkey:'ref:at:gkz',osmvalue:'209'},
'AT210':{name:'Feldkirchen',osmkey:'ref:at:gkz',osmvalue:'210'},
'AT301':{name:'Krems an der Donau (Stadt)',osmkey:'ref:at:gkz',osmvalue:'301'},
'AT302':{name:'St.Pölten (Stadt)',osmkey:'ref:at:gkz',osmvalue:'302'},
'AT303':{name:'Waidhofen an der Ybbs (Stadt)',osmkey:'ref:at:gkz',osmvalue:'303'},
'AT304':{name:'Wiener Neustadt (Stadt)',osmkey:'ref:at:gkz',osmvalue:'304'},
'AT305':{name:'Amstetten',osmkey:'ref:at:gkz',osmvalue:'305'},
'AT306':{name:'Baden',osmkey:'ref:at:gkz',osmvalue:'306'},
'AT307':{name:'Bruck an der Leitha',osmkey:'ref:at:gkz',osmvalue:'307'},
'AT308':{name:'Gänserndorf',osmkey:'ref:at:gkz',osmvalue:'308'},
'AT309':{name:'Gmünd',osmkey:'ref:at:gkz',osmvalue:'309'},
'AT310':{name:'Hollabrunn',osmkey:'ref:at:gkz',osmvalue:'310'},
'AT311':{name:'Horn',osmkey:'ref:at:gkz',osmvalue:'311'},
'AT312':{name:'Korneuburg',osmkey:'ref:at:gkz',osmvalue:'312'},
'AT313':{name:'Krems (Land)',osmkey:'ref:at:gkz',osmvalue:'313'},
'AT314':{name:'Lilienfeld',osmkey:'ref:at:gkz',osmvalue:'314'},
'AT315':{name:'Melk',osmkey:'ref:at:gkz',osmvalue:'315'},
'AT316':{name:'Mistelbach',osmkey:'ref:at:gkz',osmvalue:'316'},
'AT317':{name:'Mödling',osmkey:'ref:at:gkz',osmvalue:'317'},
'AT318':{name:'Bezirk Neunkirchen',osmkey:'ref:at:gkz',osmvalue:'318'},
'AT319':{name:'Sankt Pölten (Land)',osmkey:'ref:at:gkz',osmvalue:'319'},
'AT320':{name:'Scheibbs',osmkey:'ref:at:gkz',osmvalue:'320'},
'AT321':{name:'Tulln',osmkey:'ref:at:gkz',osmvalue:'321'},
'AT322':{name:'Waidhofen an der Thaya',osmkey:'ref:at:gkz',osmvalue:'322'},
'AT323':{name:'Wiener Neustadt (Land)',osmkey:'ref:at:gkz',osmvalue:'323'},
'AT324':{name:'Wien-Umgebung',osmkey:'ref:at:gkz',osmvalue:'324'},
'AT325':{name:'Zwettl',osmkey:'ref:at:gkz',osmvalue:'325'},
'AT401':{name:'Linz (Stadt)',osmkey:'ref:at:gkz',osmvalue:'401'},
'AT402':{name:'Steyr (Stadt)',osmkey:'ref:at:gkz',osmvalue:'402'},
'AT403':{name:'Wels',osmkey:'ref:at:gkz',osmvalue:'403'},
'AT404':{name:'Braunau am Inn',osmkey:'ref:at:gkz',osmvalue:'404'},
'AT405':{name:'Eferding',osmkey:'ref:at:gkz',osmvalue:'405'},
'AT406':{name:'Freistadt',osmkey:'ref:at:gkz',osmvalue:'406'},
'AT407':{name:'Gmunden',osmkey:'ref:at:gkz',osmvalue:'407'},
'AT408':{name:'Grieskirchen',osmkey:'ref:at:gkz',osmvalue:'408'},
'AT409':{name:'Kirchdorf an der Krems',osmkey:'ref:at:gkz',osmvalue:'409'},
'AT410':{name:'Linz-Land',osmkey:'ref:at:gkz',osmvalue:'410'},
'AT411':{name:'Perg',osmkey:'ref:at:gkz',osmvalue:'411'},
'AT412':{name:'Ried im Innkreis',osmkey:'ref:at:gkz',osmvalue:'412'},
'AT413':{name:'Rohrbach',osmkey:'ref:at:gkz',osmvalue:'413'},
'AT414':{name:'Schärding',osmkey:'ref:at:gkz',osmvalue:'414'},
'AT415':{name:'Steyr-Land',osmkey:'ref:at:gkz',osmvalue:'415'},
'AT102':{name:'Rust',osmkey:'ref:at:gkz',osmvalue:'102'},
'AT417':{name:'Vöcklabruck',osmkey:'ref:at:gkz',osmvalue:'417'},
'AT418':{name:'Wels-Land',osmkey:'ref:at:gkz',osmvalue:'418'},
'AT501':{name:'Salzburg',osmkey:'ref:at:gkz',osmvalue:'501'},
'AT502':{name:'Hallein',osmkey:'ref:at:gkz',osmvalue:'502'},
'AT503':{name:'Salzburg-Umgebung',osmkey:'ref:at:gkz',osmvalue:'503'},
'AT504':{name:'Sankt Johann im Pongau',osmkey:'ref:at:gkz',osmvalue:'504'},
'AT505':{name:'Tamsweg',osmkey:'ref:at:gkz',osmvalue:'505'},
'AT506':{name:'Zell am See',osmkey:'ref:at:gkz',osmvalue:'506'},
'AT601':{name:'Graz',osmkey:'ref:at:gkz',osmvalue:'601'},
'AT603':{name:'Deutschlandsberg',osmkey:'ref:at:gkz',osmvalue:'603'},
'AT606':{name:'Graz-Umgebung',osmkey:'ref:at:gkz',osmvalue:'606'},
'AT610':{name:'Leibnitz',osmkey:'ref:at:gkz',osmvalue:'610'},
'AT611':{name:'Leoben',osmkey:'ref:at:gkz',osmvalue:'611'},
'AT612':{name:'Liezen',osmkey:'ref:at:gkz',osmvalue:'612'},
'AT614':{name:'Murau',osmkey:'ref:at:gkz',osmvalue:'614'},
'AT616':{name:'Voitsberg',osmkey:'ref:at:gkz',osmvalue:'616'},
'AT617':{name:'Weiz',osmkey:'ref:at:gkz',osmvalue:'617'},
'AT620':{name:'Murtal',osmkey:'ref:at:gkz',osmvalue:'620'},
'AT621':{name:'Bruck-Mürzzuschlag',osmkey:'ref:at:gkz',osmvalue:'621'},
'AT622':{name:'Hartberg-Fürstenfeld',osmkey:'ref:at:gkz',osmvalue:'622'},
'AT623':{name:'Südoststeiermark',osmkey:'ref:at:gkz',osmvalue:'623'},
'AT701':{name:'Bezirk Innsbruck-Stadt',osmkey:'ref:at:gkz',osmvalue:'701'},
'AT702':{name:'Imst',osmkey:'ref:at:gkz',osmvalue:'702'},
'AT703':{name:'Innsbruck Land',osmkey:'ref:at:gkz',osmvalue:'703'},
'AT704':{name:'Kitzbühel',osmkey:'ref:at:gkz',osmvalue:'704'},
'AT705':{name:'Kufstein',osmkey:'ref:at:gkz',osmvalue:'705'},
'AT706':{name:'Landeck',osmkey:'ref:at:gkz',osmvalue:'706'},
'AT707':{name:'Lienz',osmkey:'ref:at:gkz',osmvalue:'707'},
'AT708':{name:'Reutte (Außerfern)',osmkey:'ref:at:gkz',osmvalue:'708'},
'AT709':{name:'Schwaz',osmkey:'ref:at:gkz',osmvalue:'709'},
'AT801':{name:'Bludenz',osmkey:'ref:at:gkz',osmvalue:'801'},
'AT802':{name:'Bregenz',osmkey:'ref:at:gkz',osmvalue:'802'},
'AT803':{name:'Dornbirn',osmkey:'ref:at:gkz',osmvalue:'803'},
'AT804':{name:'Feldkirch',osmkey:'ref:at:gkz',osmvalue:'804'},
'AT9':{name:'Wien',osmkey:'ref:at:gkz',osmvalue:'90001'},
'AT201':{name:'Klagenfurt (Stadt)',osmkey:'ref:at:gkz',osmvalue:'201'},
'AT21':{name:'Feldkirchen'},
'AT31':{name:'Hollabrunn'},
'AT32':{name:'Scheibbs'},
'AT41':{name:'Linz-Land'},
'AT61':{name:'Leibnitz'},
'AT62':{name:'Murtal'},
'AT1':{name:'Burgenland'},
'AT2':{name:'Kärnten'},
'AT3':{name:'Niederösterreich'},
'AT4':{name:'Oberösterreich'},
'AT5':{name:'Salzburg'},
'AT6':{name:'Steiermark'},
'AT7':{name:'Tirol'},
'AT':{name:'Österreich'},
'CH':{name:'Switzerland'},
'AT8':{name:'Vorarlberg'},
'CH08':{name:'Glarus',osmkey:'swisstopo:KANTONSNUM',osmvalue:'8'},
'CH03':{name:'Luzern',osmkey:'swisstopo:KANTONSNUM',osmvalue:'3'},
'CH02':{name:'Bern - Berne',osmkey:'swisstopo:KANTONSNUM',osmvalue:'2'},
'CH19':{name:'Aargau',osmkey:'swisstopo:KANTONSNUM',osmvalue:'19'},
'CH13':{name:'Basel-Landschaft',osmkey:'swisstopo:KANTONSNUM',osmvalue:'13'},
'CH09':{name:'Zug',osmkey:'swisstopo:KANTONSNUM',osmvalue:'9'},
'CH06':{name:'Obwalden',osmkey:'swisstopo:KANTONSNUM',osmvalue:'6'},
'CH07':{name:'Nidwalden',osmkey:'swisstopo:KANTONSNUM',osmvalue:'7'},
'CH18':{name:'Graubünden - Grigioni - Grischun',osmkey:'swisstopo:KANTONSNUM',osmvalue:'18'},
'CH15':{name:'Appenzell Ausserrhoden',osmkey:'swisstopo:KANTONSNUM',osmvalue:'15'},
'CH16':{name:'Appenzell Innerrhoden',osmkey:'swisstopo:KANTONSNUM',osmvalue:'16'},
'CH23':{name:'Valais - Wallis',osmkey:'swisstopo:KANTONSNUM',osmvalue:'23'},
'CH17':{name:'Sankt Gallen',osmkey:'swisstopo:KANTONSNUM',osmvalue:'17'},
'CH21':{name:'Ticino',osmkey:'swisstopo:KANTONSNUM',osmvalue:'21'},
'CH05':{name:'Schwyz',osmkey:'swisstopo:KANTONSNUM',osmvalue:'5'},
'CH01':{name:'Zürich',osmkey:'swisstopo:KANTONSNUM',osmvalue:'1'},
'CH20':{name:'Thurgau',osmkey:'swisstopo:KANTONSNUM',osmvalue:'20'},
'CH04':{name:'Uri',osmkey:'swisstopo:KANTONSNUM',osmvalue:'4'},
'CH14':{name:'Schaffhausen',osmkey:'swisstopo:KANTONSNUM',osmvalue:'14'},
'CH26':{name:'Jura',osmkey:'swisstopo:KANTONSNUM',osmvalue:'26'},
'CH10':{name:'Fribourg - Freiburg',osmkey:'swisstopo:KANTONSNUM',osmvalue:'10'},
'CH12':{name:'Basel-Stadt',osmkey:'swisstopo:KANTONSNUM',osmvalue:'12'},
'CH11':{name:'Solothurn',osmkey:'swisstopo:KANTONSNUM',osmvalue:'11'},
'CH25':{name:'Genève',osmkey:'swisstopo:KANTONSNUM',osmvalue:'25'},
'CH24':{name:'Neuchâtel',osmkey:'swisstopo:KANTONSNUM',osmvalue:'24'},
'CH22':{name:'Vaud',osmkey:'swisstopo:KANTONSNUM',osmvalue:'22'},

}

exports.dachKeyListShort = {"DE":
{name:"Deutschland"},
'DE09':{name:'Bayern',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'09'},
'DE01':{name:'Schleswig-Holstein',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'01'},
'DE03':{name:'Niedersachsen',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'03'},
'DE04':{name:'Bremen',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'04'},
'DE05':{name:'Nordrhein-Westfalen',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'05'},
'DE06':{name:'Hessen',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'06'},
'DE07':{name:'Rheinland-Pfalz',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'07'},
'DE08':{name:'Baden-Württemberg',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'08'},
'DE02':{name:'Hamburg',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'02'},
'DE10':{name:'Saarland',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'10'},
'DE11':{name:'Berlin',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'11'},
'DE12':{name:'Brandenburg',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'012'},
'DE13':{name:'Mecklenburg-Vorpommern',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'013'},
'DE14':{name:'Sachsen',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'14'},
'DE15':{name:'Sachsen-Anhalt',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'15'},
'DE16':{name:'Thüringen',osmkey:'de:amtlicher_gemeindeschluessel',osmvalue:'16'},
'AT9':{name:'Wien',osmkey:'ref:at:gkz',osmvalue:'90001'},
'AT21':{name:'Feldkirchen',osmkey:'ref:at:gkz',osmvalue:'21'},
'AT31':{name:'Hollabrunn',osmkey:'ref:at:gkz',osmvalue:'31'},
'AT32':{name:'Scheibbs',osmkey:'ref:at:gkz',osmvalue:'32'},
'AT41':{name:'Linz-Land',osmkey:'ref:at:gkz',osmvalue:'41'},
'AT61':{name:'Leibnitz',osmkey:'ref:at:gkz',osmvalue:'61'},
'AT62':{name:'Murtal',osmkey:'ref:at:gkz',osmvalue:'62'},
'AT1':{name:'Burgenland',osmkey:'ref:at:gkz',osmvalue:'1'},
'AT2':{name:'Kärnten',osmkey:'ref:at:gkz',osmvalue:'2'},
'AT3':{name:'Niederösterreich',osmkey:'ref:at:gkz',osmvalue:'3'},
'AT4':{name:'Oberösterreich',osmkey:'ref:at:gkz',osmvalue:'4'},
'AT5':{name:'Salzburg',osmkey:'ref:at:gkz',osmvalue:'90001'},
'AT6':{name:'Steiermark',osmkey:'ref:at:gkz',osmvalue:'6'},
'AT7':{name:'Tirol',osmkey:'ref:at:gkz',osmvalue:'7'},
'AT':{name:'Österreich'},
'CH':{name:'Switzerland'},
'AT8':{name:'Vorarlberg'},
'CH08':{name:'Glarus',osmkey:'swisstopo:KANTONSNUM',osmvalue:'8'},
'CH03':{name:'Luzern',osmkey:'swisstopo:KANTONSNUM',osmvalue:'3'},
'CH02':{name:'Bern - Berne',osmkey:'swisstopo:KANTONSNUM',osmvalue:'2'},
'CH19':{name:'Aargau',osmkey:'swisstopo:KANTONSNUM',osmvalue:'19'},
'CH13':{name:'Basel-Landschaft',osmkey:'swisstopo:KANTONSNUM',osmvalue:'13'},
'CH09':{name:'Zug',osmkey:'swisstopo:KANTONSNUM',osmvalue:'9'},
'CH06':{name:'Obwalden',osmkey:'swisstopo:KANTONSNUM',osmvalue:'6'},
'CH07':{name:'Nidwalden',osmkey:'swisstopo:KANTONSNUM',osmvalue:'7'},
'CH18':{name:'Graubünden - Grigioni - Grischun',osmkey:'swisstopo:KANTONSNUM',osmvalue:'18'},
'CH15':{name:'Appenzell Ausserrhoden',osmkey:'swisstopo:KANTONSNUM',osmvalue:'15'},
'CH16':{name:'Appenzell Innerrhoden',osmkey:'swisstopo:KANTONSNUM',osmvalue:'16'},
'CH23':{name:'Valais - Wallis',osmkey:'swisstopo:KANTONSNUM',osmvalue:'23'},
'CH17':{name:'Sankt Gallen',osmkey:'swisstopo:KANTONSNUM',osmvalue:'17'},
'CH21':{name:'Ticino',osmkey:'swisstopo:KANTONSNUM',osmvalue:'21'},
'CH05':{name:'Schwyz',osmkey:'swisstopo:KANTONSNUM',osmvalue:'5'},
'CH01':{name:'Zürich',osmkey:'swisstopo:KANTONSNUM',osmvalue:'1'},
'CH20':{name:'Thurgau',osmkey:'swisstopo:KANTONSNUM',osmvalue:'20'},
'CH04':{name:'Uri',osmkey:'swisstopo:KANTONSNUM',osmvalue:'4'},
'CH14':{name:'Schaffhausen',osmkey:'swisstopo:KANTONSNUM',osmvalue:'14'},
'CH26':{name:'Jura',osmkey:'swisstopo:KANTONSNUM',osmvalue:'26'},
'CH10':{name:'Fribourg - Freiburg',osmkey:'swisstopo:KANTONSNUM',osmvalue:'10'},
'CH12':{name:'Basel-Stadt',osmkey:'swisstopo:KANTONSNUM',osmvalue:'12'},
'CH11':{name:'Solothurn',osmkey:'swisstopo:KANTONSNUM',osmvalue:'11'},
'CH25':{name:'Genève',osmkey:'swisstopo:KANTONSNUM',osmvalue:'25'},
'CH24':{name:'Neuchâtel',osmkey:'swisstopo:KANTONSNUM',osmvalue:'24'},
'CH22':{name:'Vaud',osmkey:'swisstopo:KANTONSNUM',osmvalue:'22'},

}